/*************************************************************************
 *                        Microsoft Windows NT                           *
 *                                                                       *
 *                  Copyright(c) Microsoft Corp., 1994                   *
 *                                                                       *
 * Revision History:                                                     *
 *                                                                       *
 *   Jan. 30,94    Koti     Created                                      *
 *                                                                       *
 * Description:                                                          *
 *                                                                       *
 *   This file (lpdmsg.h) is generated by the MC tool from the file      *
 *   lpdmsg.mc                                                           *
 *                                                                       *
 *************************************************************************/



#define  LPD_SERVICE_NAME   "LPDSVC"
#define  LPD_PARMS_REGISTRY_PATH  "System\\CurrentControlSet\\Services\\LPD\\PARAMETERS"
#define  LPD_PARMNAME_MAXUSERS    "MaxConcurrentUsers"
#define  LPD_PARMNAME_JOBREMOVAL  "AllowJobRemoval"
#define  LPD_PARMNAME_PRINTRESUME "AllowPrinterResume"

#define  LPD_DEFAULT_DOC_NAME     "LPR client document"
#define  LPD_RAW_STRING           "RAW"
#define  LPD_TEXT_STRING          "TEXT"

#define  LPD_LOGO            "\n                         Windows NT 3.5 LPD Server\n"
#define  LPD_PRINTER_TITLE   "                              Printer "

   // these two lines formatted for good-looking output!
#define  LPD_QUEUE_HEADER    "\n\nOwner       Status         Jobname          Job-Id    Size   Pages  Priority"
#define  LPD_QUEUE_HEADER2   "\n----------------------------------------------------------------------------\n"

#define  LPD_SERVER_TITLE    "   Server: "
#define  LPD_QUEUE_NOPRINTER "Error: specified printer does not exist\n"
#define  LPD_QUEUE_ERRMSG    "Error: could not report status\n"
#define  LPD_NEWLINE         "\n"

#define  LPD_PRINTER_PAUSED      " (Paused)"
#define  LPD_PRINTER_PENDING_DEL " (Pending Deletion)"

   // sizeof(szIPAddr) is 16: this errmsg shouldn't exceed 15 chars!
#define  LPD_ERMSG_NO_IPADDR  "????"

#define  LPD_STR_PAUSED     "Paused"
#define  LPD_STR_ERROR      "Error"
#define  LPD_STR_DELETING   "Deleting"
#define  LPD_STR_SPOOLING   "Spooling"
#define  LPD_STR_PRINTING   "Printing"
#define  LPD_STR_OFFLINE    "Offline"
#define  LPD_STR_PAPEROUT   "Paperout"
#define  LPD_STR_PRINTED    "Printed"
#define  LPD_STR_PENDING    "Waiting"

//
//  Values are 32 bit values layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      Sev - is the severity code
//
//          00 - Success
//          01 - Informational
//          10 - Warning
//          11 - Error
//
//      C - is the Customer code flag
//
//      R - is a reserved bit
//
//      Facility - is the facility code
//
//      Code - is the facility's status code
//
//
// Define the facility codes
//


//
// Define the severity codes
//


//
// MessageId: LPDLOG_LPD_STARTED
//
// MessageText:
//
//  LPD service started successfully.
//
#define LPDLOG_LPD_STARTED               0x40000FA0L

//
// MessageId: LPDLOG_LPD_STOPPED
//
// MessageText:
//
//  LPD service stopped successfully.
//
#define LPDLOG_LPD_STOPPED               0x40000FA1L

//
// MessageId: LPDLOG_LPD_DIDNT_START
//
// MessageText:
//
//  LPD service failed to start.  The data is the error.
//
#define LPDLOG_LPD_DIDNT_START           0x80000FA2L

//
// MessageId: LPDLOG_OUT_OF_RESOURCES
//
// MessageText:
//
//  A request from client was refused because system is out of resources.
//
#define LPDLOG_OUT_OF_RESOURCES          0x80000FA3L

//
// MessageId: LPDLOG_MISBEHAVED_CLIENT
//
// MessageText:
//
//  Improper sequence of commands received from %1 : service refused.
//
#define LPDLOG_MISBEHAVED_CLIENT         0x80000FA4L

//
// MessageId: LPDLOG_UNSUPPORTED_PRINT
//
// MessageText:
//
//  Request for unsupported print format received from %1 : request ignored.
//
#define LPDLOG_UNSUPPORTED_PRINT         0x80000FA5L

//
// MessageId: LPDLOG_UNAUTHORIZED_REQUEST
//
// MessageText:
//
//  %1 on %2 requested to remove job submitted by %3 on %4: service refused.
//
#define LPDLOG_UNAUTHORIZED_REQUEST      0x80000FA6L

//
// MessageId: LPDLOG_BAD_FORMAT
//
// MessageText:
//
//  Illegal format used for commands received from %1 : service refused.
//
#define LPDLOG_BAD_FORMAT                0x80000FA7L

//
// MessageId: LPDLOG_NONEXISTENT_PRINTER
//
// MessageText:
//
//  Printer %1 specified in the request from %2 does not exist: request ignored.
//
#define LPDLOG_NONEXISTENT_PRINTER       0x80000FA8L

//
// MessageId: LPDLOG_PRINTER_RESUMED
//
// MessageText:
//
//  As per request from %1, printer %2 resumed.
//
#define LPDLOG_PRINTER_RESUMED           0x40000FA9L

//
// MessageId: LPDLOG_DIDNT_WORK
//
// MessageText:
//
//  Request from %1 could not be satisfied: possibly due to network problems
//
#define LPDLOG_DIDNT_WORK                0x80000FAAL

