/*++ BUILD Version: 0001    // Increment this if a change has global effects

Copyright (c) 1994  Microsoft Corporation

Module Name:

    dhcpmsg.h

Abstract:

    Definitions for DHCP messages.

Author:

    Madan Appiah (madana)  10-Sep-1993
    Manny Weiser 8-Dec-1992

Revision History:

Notes:

    This file is generated by the MC tool from the dhcpmsg.mc file.

    ?? NOTE : These message should go into winerror.h, until then use a
    error code range which is not used by the system.

--*/

#ifndef _DHCPMESSAGE_
#define _DHCPMESSAGE_

//
//  20000 - 20099   Reserved for DHCP server service specific errors.
//
//
//  Values are 32 bit values layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      Sev - is the severity code
//
//          00 - Success
//          01 - Informational
//          10 - Warning
//          11 - Error
//
//      C - is the Customer code flag
//
//      R - is a reserved bit
//
//      Facility - is the facility code
//
//      Code - is the facility's status code
//
//
// Define the facility codes
//


//
// Define the severity codes
//


//
// MessageId: ERROR_DHCP_REGISTRY_INIT_FAILED
//
// MessageText:
//
//  The DHCP server initialization parameters are invalid.
//
#define ERROR_DHCP_REGISTRY_INIT_FAILED  0x00004E20L

//
// MessageId: ERROR_DHCP_DATABASE_INIT_FAILED
//
// MessageText:
//
//  The DHCP server was unable to open the DHCP client database.
//
#define ERROR_DHCP_DATABASE_INIT_FAILED  0x00004E21L

//
// MessageId: ERROR_DHCP_RPC_INIT_FAILED
//
// MessageText:
//
//  The DHCP server was unable to start as an RPC server.
//
#define ERROR_DHCP_RPC_INIT_FAILED       0x00004E22L

//
// MessageId: ERROR_DHCP_NETWORK_INIT_FAILED
//
// MessageText:
//
//  The DHCP server was unable establish a sockets connection.
//
#define ERROR_DHCP_NETWORK_INIT_FAILED   0x00004E23L

//
// MessageId: ERROR_DHCP_SUBNET_EXITS
//
// MessageText:
//
//  The specified Subnet already exists.
//
#define ERROR_DHCP_SUBNET_EXITS          0x00004E24L

//
// MessageId: ERROR_DHCP_SUBNET_NOT_PRESENT
//
// MessageText:
//
//  The specified Subnet does not exist.
//
#define ERROR_DHCP_SUBNET_NOT_PRESENT    0x00004E25L    

//
// MessageId: ERROR_DHCP_PRIMARY_NOT_FOUND
//
// MessageText:
//
//  The primary host information for the specified subnet was not found.
//
#define ERROR_DHCP_PRIMARY_NOT_FOUND     0x00004E26L

//
// MessageId: ERROR_DHCP_ELEMENT_CANT_REMOVE
//
// MessageText:
//
//  The specified DHCP element cannot be removed because it has been used.
//
#define ERROR_DHCP_ELEMENT_CANT_REMOVE   0x00004E27L

//
// MessageId: ERROR_DHCP_OPTION_EXITS
//
// MessageText:
//
//  The specified option already exists.
//
#define ERROR_DHCP_OPTION_EXITS          0x00004E29L

//
// MessageId: ERROR_DHCP_OPTION_NOT_PRESENT
//
// MessageText:
//
//  The specified option does not exist.
//
#define ERROR_DHCP_OPTION_NOT_PRESENT    0x00004E2AL    

//
// MessageId: ERROR_DHCP_ADDRESS_NOT_AVAILABLE
//
// MessageText:
//
//  The specified address is not available.
//
#define ERROR_DHCP_ADDRESS_NOT_AVAILABLE 0x00004E2BL    

//
// MessageId: ERROR_DHCP_RANGE_FULL
//
// MessageText:
//
//  The specified Range is full.
//
#define ERROR_DHCP_RANGE_FULL            0x00004E2CL    

//
// MessageId: ERROR_DHCP_JET_ERROR
//
// MessageText:
//
//  An error occurred while accessing the DHCP database; Look at the
//  DHCP server event log for more information.
//
#define ERROR_DHCP_JET_ERROR             0x00004E2DL    

//
// MessageId: ERROR_DHCP_CLIENT_EXISTS
//
// MessageText:
//
//  The specified Client already exists in the database.
//
#define ERROR_DHCP_CLIENT_EXISTS         0x00004E2EL    

//
// MessageId: ERROR_DHCP_INVALID_DHCP_MESSAGE
//
// MessageText:
//
//  The DHCP server received an invalid message.
//
#define ERROR_DHCP_INVALID_DHCP_MESSAGE  0x00004E2FL    

//
// MessageId: ERROR_DHCP_INVALID_DHCP_CLIENT
//
// MessageText:
//
//  The DHCP server received a message from an invalid client.
//
#define ERROR_DHCP_INVALID_DHCP_CLIENT   0x00004E30L    

//
// MessageId: ERROR_DHCP_SERVICE_PAUSED
//
// MessageText:
//
//  The DHCP server service is paused.
//
#define ERROR_DHCP_SERVICE_PAUSED        0x00004E31L    

//
// MessageId: ERROR_DHCP_NOT_RESERVED_CLIENT
//
// MessageText:
//
//  The specified client is not a reserved client.
//
#define ERROR_DHCP_NOT_RESERVED_CLIENT   0x00004E32L    

//
// MessageId: ERROR_DHCP_RESERVED_CLIENT
//
// MessageText:
//
//  The specified client is a reserved client.
//
#define ERROR_DHCP_RESERVED_CLIENT       0x00004E33L    

//
// MessageId: ERROR_DHCP_RANGE_TOO_SMALL
//
// MessageText:
//
//  The specified IpRange is too small.
//
#define ERROR_DHCP_RANGE_TOO_SMALL       0x00004E34L    

//
// MessageId: ERROR_DHCP_IPRANGE_EXITS
//
// MessageText:
//
//  The specified IpRange already exists.
//
#define ERROR_DHCP_IPRANGE_EXITS         0x00004E35L    

//
// MessageId: ERROR_DHCP_RESERVEDIP_EXITS
//
// MessageText:
//
//  The specified IP address is already used by another client.
//
#define ERROR_DHCP_RESERVEDIP_EXITS      0x00004E36L    

//
// MessageId: ERROR_DHCP_INVALID_RANGE
//
// MessageText:
//
//  The specified range either overlaps with an already existing range or is
//  invalid.
//
#define ERROR_DHCP_INVALID_RANGE         0x00004E37L    

//
// MessageId: ERROR_DHCP_RANGE_EXTENDED
//
// MessageText:
//
//  The specified range is extension of an already existing range.
//
#define ERROR_DHCP_RANGE_EXTENDED        0x00004E38L    

//
//  1000 - 1099   Reserved for DHCP server events.
//
//
// MessageId: EVENT_SERVER_UNKNOWN_OPTION
//
// MessageText:
//
//  The DHCP Server received an unknown option %1 of length %2. The raw option
//  data is given below.
//
#define EVENT_SERVER_UNKNOWN_OPTION      0x000003E8L

//
// MessageId: EVENT_SERVER_FAILED_REGISTER_SC
//
// MessageText:
//
//  The DHCP Server failed to register with Service Controller. The
//  following error occurred: %n%1.
//
#define EVENT_SERVER_FAILED_REGISTER_SC  0x000003E9L

//
// MessageId: EVENT_SERVER_INIT_DATA_FAILED
//
// MessageText:
//
//  The DHCP server failed to initialize its global data. The following
//  error occurred: %n%1
//
#define EVENT_SERVER_INIT_DATA_FAILED    0x000003EAL

//
// MessageId: EVENT_SERVER_INIT_REGISTRY_FAILED
//
// MessageText:
//
//  The DHCP server failed to initialize its registry data. The following
//  error occurred: %n%1
//
#define EVENT_SERVER_INIT_REGISTRY_FAILED 0x000003EBL

//
// MessageId: EVENT_SERVER_INIT_DATABASE_FAILED
//
// MessageText:
//
//  The DHCP server failed to initialize the database. The following
//  error occurred: %n%1
//
#define EVENT_SERVER_INIT_DATABASE_FAILED 0x000003ECL

//
// MessageId: EVENT_SERVER_INIT_WINSOCK_FAILED
//
// MessageText:
//
//  The DHCP server failed to initialize Winsock startup. The following
//  error occurred: %n%1
//
#define EVENT_SERVER_INIT_WINSOCK_FAILED 0x000003EDL

//
// MessageId: EVENT_SERVER_INIT_RPC_FAILED
//
// MessageText:
//
//  The DHCP Server Failed to start the RPC server. The following error
//  occurred : %n%1
//
#define EVENT_SERVER_INIT_RPC_FAILED     0x000003EEL

//
// MessageId: EVENT_SERVER_INIT_SOCK_FAILED
//
// MessageText:
//
//  The DHCP server failed to initialize winsock data. The following
//  error occurred: %n%1
//
#define EVENT_SERVER_INIT_SOCK_FAILED    0x000003EFL

//
// MessageId: EVENT_SERVER_SHUTDOWN
//
// MessageText:
//
//  The DHCP server is shutting down due to the following error: %n%1
//
#define EVENT_SERVER_SHUTDOWN            0x000003F0L

//
// MessageId: EVENT_SERVER_CLIENT_CLEANUP
//
// MessageText:
//
//  The DHCP server encountered the following error when cleaning up the
//  pending user records: %n%1
//
#define EVENT_SERVER_CLIENT_CLEANUP      0x000003F1L

//
// MessageId: EVENT_SERVER_DATABASE_CLEANUP
//
// MessageText:
//
//  The DHCP server encoutered the following error when cleaning up the user
//  database: %n%1
//
#define EVENT_SERVER_DATABASE_CLEANUP    0x000003F2L

//
// MessageId: EVENT_SERVER_LEASE_NACK
//
// MessageText:
//
//  The DHCP server issued a NACK to the client (%2) for the address (%1)
//  request.
//
#define EVENT_SERVER_LEASE_NACK          0x000003F3L

//
// MessageId: EVENT_SERVER_LEASE_DECLINED
//
// MessageText:
//
//  The DHCP Client (%2) declined the address (%1).
//
#define EVENT_SERVER_LEASE_DECLINED      0x000003F4L

//
// MessageId: EVENT_SERVER_LEASE_RELEASE
//
// MessageText:
//
//  The DHCP Client (%2) released the address (%1).
//
#define EVENT_SERVER_LEASE_RELEASE       0x000003F5L

//
// MessageId: EVENT_SERVER_JET_ERROR
//
// MessageText:
//
//  The JET Database call returned the following Error : %1.
//
#define EVENT_SERVER_JET_ERROR           0x000003F6L

//
// MessageId: EVENT_SERVER_JET_WARNING
//
// MessageText:
//
//  The JET Database call returned the following Warning : %1.
//
#define EVENT_SERVER_JET_WARNING         0x000003F7L

//
// MessageId: EVENT_SERVER_DATABASE_BACKUP
//
// MessageText:
//
//  The DHCP server encoutered the following error when backing up the
//  user database: %n%1
//
#define EVENT_SERVER_DATABASE_BACKUP     0x000003F8L

//
// MessageId: EVENT_SERVER_CONFIG_BACKUP
//
// MessageText:
//
//  The DHCP server encoutered the following error when backing up the
//  registry configuration: %n%1
//
#define EVENT_SERVER_CONFIG_BACKUP       0x000003F9L

//
// MessageId: EVENT_SERVER_DATABASE_RESTORE_FAILED
//
// MessageText:
//
//  The DHCP server failed to restore the database. The following
//  error occurred: %n%1
//
#define EVENT_SERVER_DATABASE_RESTORE_FAILED 0x000003FAL

//
// MessageId: EVENT_SERVER_CONFIG_RESTORE_FAILED
//
// MessageText:
//
//  The DHCP server failed to restore the dhcp registry configuration. The
//  following error occurred: %n%1
//
#define EVENT_SERVER_CONFIG_RESTORE_FAILED 0x000003FBL

//
// MessageId: EVENT_SERVER_LOW_ADDRESS_WARNING
//
// MessageText:
//
//  Scope %1 is %2 percent utilized with only %3 IP addresses remaining.
//
#define EVENT_SERVER_LOW_ADDRESS_WARNING 0x000003FCL

#endif // _DHCPMESSAGE_
