#define FI_CLIENTCOPYDDEIN1                                         0
#define FI_CLIENTCOPYDDEIN2                                         1
#define FI_CLIENTCOPYDDEOUT1                                        2
#define FI_CLIENTCOPYDDEOUT2                                        3
#define FI_CLIENTDELETEDC                                           4
#define FI_CLIENTEVENTCALLBACK                                      5
#define FI_CLIENTFINDCLOSE                                          6
#define FI_CLIENTFINDFIRSTFILE                                      7
#define FI_CLIENTFINDNEXTFILE                                       8
#define FI_CLIENTFREEDDEHANDLE                                      9
#define FI_CLIENTFREELIBRARY                                        10
#define FI_CLIENTGETCURRENTDIRECTORY                                11
#define FI_CLIENTGETDDEFLAGS                                        12
#define FI_CLIENTGETDDEHOOKDATA                                     13
#define FI_CLIENTGETLISTBOXSTRING                                   14
#define FI_CLIENTGETLOGICALDRIVES                                   15
#define FI_CLIENTGETTHREADLOCALE                                    16
#define FI_CLIENTLOADCREATECURSORICON                               17
#define FI_CLIENTLOADCREATEMENU                                     18
#define FI_CLIENTLOADLIBRARY                                        19
#define FI_CLIENTSETCURRENTDIRECTORY                                20
#define FI_CLIENTWINEXEC                                            21
#define FI_FNCOPYDATA                                               22
#define FI_FNCOPYGLOBALDATA                                         23
#define FI_FNDWORD                                                  24
#define FI_FNDWORDOPTINLPMSG                                        25
#define FI_FNDRAG                                                   26
#define FI_FNGDIHANDLE                                              27
#define FI_FNGETTEXTLENGTHS                                         28
#define FI_FNHKINDWORD                                              29
#define FI_FNHKINLPCBTACTIVATESTRUCT                                30
#define FI_FNHKINLPCBTCSTRUCT                                       31
#define FI_FNHKINLPCBTMDICCSTRUCT                                   32
#define FI_FNHKINLPDEBUGHOOKSTRUCT                                  33
#define FI_FNHKINLPMOUSEHOOKSTRUCT                                  34
#define FI_FNHKINLPMSG                                              35
#define FI_FNHKINLPRECT                                             36
#define FI_FNHKOPTINLPEVENTMSG                                      37
#define FI_FNINCNTOUTSTRING                                         38
#define FI_FNINCNTOUTSTRINGNULL                                     39
#define FI_FNINLPCLIENTCREATESTRUCT                                 40
#define FI_FNINLPCOMPAREITEMSTRUCT                                  41
#define FI_FNINLPDELETEITEMSTRUCT                                   42
#define FI_FNINLPDRAWITEMSTRUCT                                     43
#define FI_FNINLPDROPSTRUCT                                         44
#define FI_FNINLPMDICHILDCREATESTRUCT                               45
#define FI_FNINLPMDICREATESTRUCT                                    46
#define FI_FNINLPMEASUREITEMSTRUCT                                  47
#define FI_FNINLPNORMALCREATESTRUCT                                 48
#define FI_FNINLPWINDOWPOS                                          49
#define FI_FNINOUTLPPOINT5                                          50
#define FI_FNINOUTLPRECT                                            51
#define FI_FNINOUTNCCALCSIZE                                        52
#define FI_FNINOUTLPWINDOWPOS                                       53
#define FI_FNINPAINTCLIPBRD                                         54
#define FI_FNINSIZECLIPBRD                                          55
#define FI_FNINDESTROYCLIPBRD                                       56
#define FI_FNINSTRING                                               57
#define FI_FNINSTRINGNULL                                           58
#define FI_FNINWPARAMCHAR                                           59
#define FI_FNOUTLPRECT                                              60
#define FI_FNOUTSTRING                                              61
#define FI_FNPAINT                                                  62
#define FI_FNPOPTINLPUINT                                           63
#define FI_FNPOUTLPINT                                              64
#define FI_FNSENTDDEMSG                                             65
#define FI_FNINLPHLPSTRUCT                                          66
#define FI_GETEDITDS                                                67
#define FI_RELEASEEDITDS                                            68
#define FI_WOWDLGINIT                                               69
#define FI_FNOUTDWORDDWORD                                          70
#define FI_FNOUTDWORDINDWORD                                        71
#define FI_FNOPTOUTLPDWORDOPTOUTLPDWORD                             72
#define FI_FNNEXTMENU                                               73
#define FI_COPYFROMCLIENT                                           74
#define FI_COPYTOCLIENT                                             75
#define FI_SETFAKEDIALOGCLASS                                       76
