#define SFI__BEGINDEFERWINDOWPOS                                     0
#define SFI__COUNTCLIPBOARDFORMATS                                   1
#define SFI__CREATEMENU                                              2
#define SFI__CREATEPOPUPMENU                                         3
#define SFI__CSDDEUNINITIALIZE                                       4
#define SFI__DESTROYCARET                                            5
#define SFI__ENUMCLIPBOARDFORMATS                                    6
#define SFI__GETCARETBLINKTIME                                       7
#define SFI__GETCLIPBOARDOWNER                                       8
#define SFI__GETCLIPBOARDVIEWER                                      9
#define SFI__GETDIALOGBASEUNITS                                      10
#define SFI__GETDOUBLECLICKTIME                                      11
#define SFI__GETFOREGROUNDWINDOW                                     12
#define SFI__GETINPUTDESKTOP                                         13
#define SFI__GETINPUTSTATE                                           14
#define SFI__GETKEYBOARDTYPE                                         15
#define SFI__GETMENUCHECKMARKDIMENSIONS                              16
#define SFI__GETMESSAGEPOS                                           17
#define SFI__GETOPENCLIPBOARDWINDOW                                  18
#define SFI__GETQUEUESTATUS                                          19
#define SFI__ISCLIPBOARDFORMATAVAILABLE                              20
#define SFI__KILLSYSTEMTIMER                                         21
#define SFI__MESSAGEBEEP                                             22
#define SFI__POSTQUITMESSAGE                                         23
#define SFI__RELEASECAPTURE                                          24
#define SFI__RELEASEDC                                               25
#define SFI__REPLYMESSAGE                                            26
#define SFI__SETCARETBLINKTIME                                       27
#define SFI__SETCARETPOS                                             28
#define SFI__SETCURSORPOS                                            29
#define SFI__SETDOUBLECLICKTIME                                      30
#define SFI__SHOWCURSOR                                              31
#define SFI__SHOWSTARTGLASS                                          32
#define SFI__SWAPMOUSEBUTTON                                         33
#define SFI__UNHOOKWINDOWSHOOK                                       34
#define SFI__WINDOWFROMDC                                            35
#define SFI_CURRENTTASKLOCK                                          36
#define SFI_LW_LOADFONTS                                             37
#define SFI_XXXARRANGEICONICWINDOWS                                  38
#define SFI_XXXCALCCHILDSCROLL                                       39
#define SFI_XXXCASCADECHILDWINDOWS                                   40
#define SFI_XXXCLOSEWINDOW                                           41
#define SFI_XXXDIRECTEDYIELD                                         42
#define SFI_XXXDRAWMENUBAR                                           43
#define SFI_XXXEMPTYCLIPBOARD                                        44
#define SFI_XXXENABLEWINDOW                                          45
#define SFI_XXXENDDIALOG                                             46
#define SFI_XXXFLASHWINDOW                                           47
#define SFI_XXXISDLGBUTTONCHECKED                                    48
#define SFI_XXXOPENICON                                              49
#define SFI_XXXREALIZEPALETTE                                        50
#define SFI_XXXREGISTERUSERHUNGAPPHANDLERS                           51
#define SFI_XXXSERVERCLOSECLIPBOARD                                  52
#define SFI_XXXSETFOREGROUNDWINDOW                                   53
#define SFI_XXXSETWINDOWFULLSCREENSTATE                              54
#define SFI_XXXSHOWOWNEDPOPUPS                                       55
#define SFI_XXXTILECHILDWINDOWS                                      56
#define SFI_XXXUPDATEWINDOW                                          57
#define SFI_XXXVALIDATERGN                                           58
#define SFI_XXXEXITWINDOWSEX                                         59
#define SFI__REGISTERSYSTEMTHREAD                                    60
