// ; The below messages have an hwnd as the first parameter.  The hwnd is not locked
#define FI_CHILDWINDOWFROMPOINT                                     0
#define FI_CSCREATECARET                                            1
#define FI_CSENDPAINT                                               2
#define FI_CSEXCLUDEUPDATERGN                                       3
#define FI_CSGETCPD                                                 4
#define FI_DDEGETQUALITYOFSERVICE                                   5
#define FI_DDESETQUALITYOFSERVICE                                   6
#define FI_DESTROYWINDOW                                            7
#define FI_GETCLASSWORD                                             8
#define FI_GETINTERNALWINDOWPOS                                     9
#define FI_GETPROP                                                  10
#define FI_GETSYSTEMMENU                                            11
#define FI_GETWINDOWPLACEMENT                                       12
#define FI_IMPERSONATEDDECLIENTWINDOW                               13
#define FI_INTERNALGETWINDOWTEXT                                    14
#define FI_MAPDIALOGRECT                                            15
#define FI_REGISTERTASKLIST                                         16
#define FI_REMOVEPROP                                               17
#define FI_SERVERGETCLASSDATA                                       18
#define FI_SERVERGETCLASSNAME                                       19
#define FI_SERVERGETWINDOWLONG                                      20
#define FI_SERVERSETCLASSLONG                                       21
#define FI_SERVERSETWINDOWLONG                                      22
#define FI_SETCLASSWORD                                             23
#define FI_SETLOGONNOTIFYWINDOW                                     24
#define FI_SETPROP                                                  25
#define FI_SETWINDOWWORD                                            26
#define FI_ENDTRANSLATEHWND                                         27
// ; The below messages do not have any parameters other than the hwnd
#define FI_FNDWORD                                                  27
#define FI_FNINWPARAMCHAR                                           28
#define FI_FNPAINT                                                  29
#define FI_FNSETLOCALE                                              30
#define FI_ENDTRANSLATECALL                                         31
// ; All below messages have an hwnd that is locked
#define FI_CHANGECLIPBOARDCHAIN                                     31
#define FI_CHECKDLGBUTTON                                           32
#define FI_CHECKRADIOBUTTON                                         33
#define FI_CSBEGINPAINT                                             34
#define FI_CSGETUPDATERGN                                           35
#define FI_CSINVALIDATERGN                                          36
#define FI_DLGDIRLISTCOMBOBOX                                       37
#define FI_DLGDIRSELECTCOMBOBOXEX                                   38
#define FI_DLGDIRSELECTEX                                           39
#define FI_DRAGDETECT                                               40
#define FI_DRAGOBJECT                                               41
#define FI_ENABLESCROLLBAR                                          42
#define FI_FILLWINDOW                                               43
#define FI_FNCOPYDATA                                               44
#define FI_FNCOPYGLOBALDATA                                         45
#define FI_FNDDEINIT                                                46
#define FI_FNDRAG                                                   47
#define FI_FNDWORDOPTINLPMSG                                        48
#define FI_FNGETTEXTLENGTHS                                         49
#define FI_FNINCNTOUTSTRINGNULL                                     50
#define FI_FNINLPCLIENTCREATESTRUCT                                 51
#define FI_FNINLPCOMPAREITEMSTRUCT                                  52
#define FI_FNINLPDELETEITEMSTRUCT                                   53
#define FI_FNINLPDRAWITEMSTRUCT                                     54
#define FI_FNINLPDROPSTRUCT                                         55
#define FI_FNINLPHLPSTRUCT                                          56
#define FI_FNINLPMDICHILDCREATESTRUCT                               57
#define FI_FNINLPMDICREATESTRUCT                                    58
#define FI_FNINLPMEASUREITEMSTRUCT                                  59
#define FI_FNINLPNORMALCREATESTRUCT                                 60
#define FI_FNINLPWINDOWPOS                                          61
#define FI_FNINOUTLPPOINT5                                          62
#define FI_FNINOUTLPRECT                                            63
#define FI_FNINOUTLPWINDOWPOS                                       64
#define FI_FNINOUTNCCALCSIZE                                        65
#define FI_FNINSTRING                                               66
#define FI_FNINSTRINGNULL                                           67
#define FI_FNNEXTMENU                                               68
#define FI_FNOPTOUTLPDWORDOPTOUTLPDWORD                             69
#define FI_FNOUTDWORDDWORD                                          70
#define FI_FNOUTDWORDINDWORD                                        71
#define FI_FNOUTLPRECT                                              72
#define FI_FNOUTSTRING                                              73
#define FI_FNPOPTINLPUINT                                           74
#define FI_FNPOUTLPINT                                              75
#define FI_FNSENTDDEMSG                                             76
#define FI_FNWMCTLCOLOR                                             77
#define FI_GETCONTROLBRUSH                                          78
#define FI_GETDLGITEMINT                                            79
#define FI_GETDLGITEMTEXT                                           80
#define FI_GETUPDATERECT                                            81
#define FI_GETWINDOWTEXTLENGTH                                      82
#define FI_HILITEMENUITEM                                           83
#define FI_PAINTRECT                                                84
#define FI_REDRAWWINDOW                                             85
#define FI_SCROLLCHILDREN                                           86
#define FI_SCROLLWINDOW                                             87
#define FI_SCROLLWINDOWEX                                           88
#define FI_SERVERGETLISTBOXSTRING                                   89
#define FI_SETDLGITEMINT                                            90
#define FI_SETDLGITEMTEXT                                           91
#define FI_SETINTERNALWINDOWPOS                                     92
#define FI_SETMENU                                                  93
#define FI_SETPARENT                                                94
#define FI_SETSCROLLPOS                                             95
#define FI_SETSCROLLRANGE                                           96
#define FI_SETSYSTEMMENU                                            97
#define FI_SETSYSTEMTIMER                                           98
#define FI_SETWINDOWPLACEMENT                                       99
#define FI_SETWINDOWTEXT                                            100
#define FI_SHOWSCROLLBAR                                            101
#define FI_SERVERCALLHWNDLOCK                                       102
#define FI_SERVERCALLHWNDPARAMLOCK                                  103
#define FI_ENDTRANSLATELOCK                                         104
// ; The rest of the messages below are random messages
#define FI_ACTIVATEKEYBOARDLAYOUT                                   104
#define FI_APPENDMENU                                               105
#define FI_ATTACHTHREADINPUT                                        106
#define FI_BRINGWINDOWTOTOP                                         107
#define FI_CALLMSGFILTER                                            108
#define FI_CLIPCURSOR                                               109
#define FI_COPYACCELERATORTABLE                                     110
#define FI_CREATECURSOR                                             111
#define FI_CREATEICON                                               112
#define FI_CREATEICONINDIRECT                                       113
#define FI_CREATEMDIWINDOW                                          114
#define FI_CSCREATEWINDOWEX                                         115
#define FI_CSDDEINITIALIZE                                          116
#define FI_CSDRAWICON                                               117
#define FI_CSEVENT                                                  118
#define FI_CSGETDC                                                  119
#define FI_CSGETDCEX                                                120
#define FI_CSGETWINDOWDC                                            121
#define FI_CSSCROLLDC                                               122
#define FI_CSSETMENUITEMBITMAPS                                     123
#define FI_CSUPDATEINSTANCE                                         124
#define FI_DEFERWINDOWPOS                                           125
#define FI_DELETEMENU                                               126
#define FI_DESTROYACCELERATORTABLE                                  127
#define FI_DESTROYCURSOR                                            128
#define FI_DESTROYMENU                                              129
#define FI_DLGDIRLIST                                               130
#define FI_DRAWFRAME                                                131
#define FI_DRAWTEXT                                                 132
#define FI_ENDDEFERWINDOWPOS                                        133
#define FI_ENDMENU                                                  134
#define FI_ENDTASK                                                  135
#define FI_ENUMDISPLAYDEVICES                                       136
#define FI_ENUMDISPLAYDEVICEMODES                                   137
#define FI_FINDWINDOW                                               138
#define FI_GETASYNCKEYSTATE                                         139
#define FI_GETCLASSINFO                                             140
#define FI_GETCLASSWOWWORDS                                         141
#define FI_GETCLIPCURSOR                                            142
#define FI_GETCLIPBOARDFORMATNAME                                   143
#define FI_GETICONINFO                                              144
#define FI_GETINPUTEVENT                                            145
#define FI_GETKEYNAMETEXT                                           146
#define FI_GETKEYBOARDLAYOUTNAME                                    147
#define FI_GETMENUSTRING                                            148
#define FI_GETPRIORITYCLIPBOARDFORMAT                               149
#define FI_GETTABBEDTEXTEXTENT                                      150
#define FI_HIDECARET                                                151
#define FI_INITTASK                                                 152
#define FI_INSERTMENU                                               153
#define FI_INVALIDATERECT                                           154
#define FI_ISDIALOGMESSAGE                                          155
#define FI_KEYBD_EVENT                                              156
#define FI_KILLTIMER                                                157
#define FI_LOADKEYBOARDLAYOUT                                       158
#define FI_LOCKWINDOWSTATION                                        159
#define FI_LOCKWINDOWUPDATE                                         160
#define FI_MAPVIRTUALKEY                                            161
#define FI_MESSAGEBOXEX                                             162
#define FI_MODIFYMENU                                               163
#define FI_MOUSE_EVENT                                              164
#define FI_MOVEWINDOW                                               165
#define FI_OEMKEYSCAN                                               166
#define FI_OPENCLIPBOARD                                            167
#define FI_QUERYSENDMESSAGE                                         168
#define FI_REGISTERCLASSWOW                                         169
#define FI_REGISTERCLIPBOARDFORMAT                                  170
#define FI_REGISTERHOTKEY                                           171
#define FI_REGISTERWINDOWMESSAGE                                    172
#define FI_REMOVEMENU                                               173
#define FI_SERVERBUILDHWNDLIST                                      174
#define FI_SERVERBUILDPROPLIST                                      175
#define FI_SERVERBUILDNAMELIST                                      176
#define FI_SERVERCHANGEMENU                                         177
#define FI_SERVERCHECKMENUITEM                                      178
#define FI_SERVERCONVERTMEMHANDLE                                   179
#define FI_SERVERCREATEACCELERATORTABLE                             180
#define FI_SERVERCREATEDIALOG                                       181
#define FI_SERVERCREATELOCALMEMHANDLE                               182
#define FI_SERVERDIALOGBOX                                          183
#define FI_SERVERDISPATCHMESSAGE                                    184
#define FI_SERVERENABLEMENUITEM                                     185
#define FI_SERVERGETCLIPBOARDDATA                                   186
#define FI_SERVERGETMESSAGE                                         187
#define FI_SERVERINITIALIZETHREADINFO                               188
#define FI_SERVERLOADCREATEBITMAP                                   189
#define FI_SERVERLOADCREATECURSORICON                               190
#define FI_SERVERLOADCREATEMENU                                     191
#define FI_SERVERPEEKMESSAGE                                        192
#define FI_SERVERPOSTMESSAGE                                        193
#define FI_SERVERPOSTTHREADMESSAGE                                  194
#define FI_SERVERSENDNOTIFYMESSAGE                                  195
#define FI_SERVERSENDMESSAGECALLBACK                                196
#define FI_SERVERSETCLIPBOARDDATA                                   197
#define FI_SERVERSETWINDOWSHOOKEX                                   198
#define FI_SERVERTRANSLATEACCELERATOR                               199
#define FI_SERVERWAITFORINPUTIDLE                                   200
#define FI_SERVERWINHELP                                            201
#define FI_SETACTIVEWINDOW                                          202
#define FI_SETCAPTURE                                               203
#define FI_SETCLIPBOARDVIEWER                                       204
#define FI_SETCURSOR                                                205
#define FI_SETCURSORCONTENTS                                        206
#define FI_SETFOCUS                                                 207
#define FI_SETKEYBOARDSTATE                                         208
#define FI_SETSYSCOLORS                                             209
#define FI_SETSYSTEMCURSOR                                          210
#define FI_LOADCURSORFROMFILE                                       211
#define FI_GETCURSORINFO                                            212
#define FI_SETTIMER                                                 213
#define FI_SETWINDOWPOS                                             214
#define FI_SETWINDOWSHOOKAW                                         215
#define FI_SETWINDOWSTATIONUSER                                     216
#define FI_SHOWCARET                                                217
#define FI_SHOWWINDOW                                               218
#define FI_SWITCHDESKTOP                                            219
#define FI_SYSTEMPARAMETERSINFO                                     220
#define FI_TABBEDTEXTOUT                                            221
#define FI_TOUNICODE                                                222
#define FI_TRACKPOPUPMENU                                           223
#define FI_TRANSLATEMDISYSACCEL                                     224
#define FI_TRANSLATEMESSAGE                                         225
#define FI_UNHOOKWINDOWSHOOKEX                                      226
#define FI_UNLOADKEYBOARDLAYOUT                                     227
#define FI_UNLOCKWINDOWSTATION                                      228
#define FI_UNREGISTERCLASS                                          229
#define FI_UNREGISTERHOTKEY                                         230
#define FI_UPDATEPERUSERSYSTEMPARAMETERS                            231
#define FI_VALIDATERECT                                             232
#define FI_VKKEYSCAN                                                233
#define FI_WAITMESSAGE                                              234
#define FI_WINDOWFROMPOINT                                          235
#define FI_WOWCLEANUP                                               236
#define FI_WOWFINDWINDOW                                            237
#define FI_YIELDTASK                                                238
#define FI_FNHKINDWORD                                              239
#define FI_FNHKINLPCBTACTIVATESTRUCT                                240
#define FI_FNHKINLPDEBUGHOOKSTRUCT                                  241
#define FI_FNHKINLPMOUSEHOOKSTRUCT                                  242
#define FI_FNHKINLPMSG                                              243
#define FI_FNHKINLPRECT                                             244
#define FI_FNHKOPTINLPEVENTMSG                                      245
#define FI_FNINCNTOUTSTRING                                         246
#define FI_FNINPAINTCLIPBRD                                         247
#define FI_FNINSIZECLIPBRD                                          248
#define FI_FNHKINLPCBTCSTRUCT                                       249
#define FI_FNHKINLPCBTMDICCSTRUCT                                   250
#define FI_GETMENUINDEX                                             251
#define FI_RESYNCKEYSTATE                                           252
#define FI_SERVERCALLNOPARAM                                        253
#define FI_SERVERCALLNOPARAMTRANSLATE                               254
#define FI_SERVERCALLONEPARAM                                       255
#define FI_SERVERCALLONEPARAMTRANSLATE                              256
#define FI_SERVERCALLTWOPARAM                                       257
#define FI_WOWWAITFORMSGANDEVENT                                    258
#define FI_ENDTRANSLATEQLPC                                         259
// ; The rest of the messages below are LPC functions
#define FI_CLOSEDESKTOP                                             259
#define FI_CLOSEWINDOWSTATION                                       260
#define FI_CREATEDESKTOPW                                           261
#define FI_CREATEWINDOWSTATIONW                                     262
#define FI_GETUSEROBJECTINFORMATION                                 263
#define FI_GETTHREADDESKTOP                                         264
#define FI_GETPROCESSWINDOWSTATION                                  265
#define FI_SETDEBUGERRORLEVEL                                       266
#define FI_OPENDESKTOPW                                             267
#define FI_OPENINPUTDESKTOP                                         268
#define FI_OPENWINDOWSTATIONW                                       269
#define FI_REGISTERLOGONPROCESS                                     270
#define FI_SERVERGETOBJECTSECURITY                                  271
#define FI_SERVERSETOBJECTSECURITY                                  272
#define FI_SETPROCESSWINDOWSTATION                                  273
#define FI_SETTHREADDESKTOP                                         274
#define FI_SETUSEROBJECTINFORMATION                                 275
