/*
Copyright (c) 1992  Maynard Electrionics, Inc.

Module Name:

    bkuevent.h

Abstract:

    Definitions for ntbackup events.

Author:

    David Van Camp

Revision History:

Notes:

    This file is generated by the MC tool from the bkuevent.mc file.

--*/

#ifndef _BKUEVENT_
#define _BKUEVENT_



/////////////////////////////////////////////////////////////////////////
//
// NT Backup Events
//
// Codes 8000 - 8008
//
/////////////////////////////////////////////////////////////////////////



//
//  Values are 32 bit values layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      Sev - is the severity code
//
//          00 - Success
//          01 - Informational
//          10 - Warning
//          11 - Error
//
//      C - is the Customer code flag
//
//      R - is a reserved bit
//
//      Facility - is the facility code
//
//      Code - is the facility's status code
//
//
// Define the facility codes
//


//
// Define the severity codes
//


//
// MessageId: EVENT_BKUP_BEGINBACKUP
//
// MessageText:
//
//  Begin Backup of '%1'
//      Verify:  %2  
//        Mode:  %3  
//        Type:  %4
//
#define EVENT_BKUP_BEGINBACKUP           0x00001F40L

//
// MessageId: EVENT_BKUP_ENDBACKUP
//
// MessageText:
//
//  End Backup of '%1'
//      Verify:  %2  
//        Mode:  %3
//        Type:  %4
//
#define EVENT_BKUP_ENDBACKUP             0x00001F41L

//
// MessageId: EVENT_BKUP_BEGINRESTORE
//
// MessageText:
//
//  Begin Restore to '%1'
//      Verify:  %2
//
#define EVENT_BKUP_BEGINRESTORE          0x00001F42L

//
// MessageId: EVENT_BKUP_ENDRESTORE
//
// MessageText:
//
//  End Restore to '%1'
//      Verify:  %2
//
#define EVENT_BKUP_ENDRESTORE            0x00001F43L

//
// MessageId: EVENT_BKUP_BEGINERASE
//
// MessageText:
//
//  Begin Erase
//
#define EVENT_BKUP_BEGINERASE            0x00001F44L

//
// MessageId: EVENT_BKUP_ENDERASE
//
// MessageText:
//
//  End Erase
//
#define EVENT_BKUP_ENDERASE              0x00001F45L

//
// MessageId: EVENT_BKUP_BEGINRETENSION
//
// MessageText:
//
//  Begin Retension
//
#define EVENT_BKUP_BEGINRETENSION        0x00001F46L

//
// MessageId: EVENT_BKUP_ENDRETENSION
//
// MessageText:
//
//  End Retension
//
#define EVENT_BKUP_ENDRETENSION          0x00001F47L

//
// MessageId: EVENT_BKUP_BEGINVERIFY
//
// MessageText:
//
//  Begin Verify to '%1'
//
#define EVENT_BKUP_BEGINVERIFY           0x00001F48L

//
// MessageId: EVENT_BKUP_ENDVERIFY
//
// MessageText:
//
//  End Verify to '%1'
//
#define EVENT_BKUP_ENDVERIFY             0x00001F49L

#endif // _BKUEVENT_
