/*++ BUILD Version: 0001    // Increment this if a change has global effects

Copyright (c) 1994  Microsoft Corporation

Module Name:

    sdevents.h

Abstract:

    Definitions for Save Dump Utility.

Author:

    Darryl Havens (darrylh) 12-jan-1994

Revision History:

Notes:

    This file is generated by the MC tool from the sdevents.mc file.

--*/


#ifndef _SDEVENT_
#define _SDEVENT_


/////////////////////////////////////////////////////////////////////////
//
// SaveDump Events (1000 - 1999)
//
/////////////////////////////////////////////////////////////////////////

//
//  Values are 32 bit values layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      Sev - is the severity code
//
//          00 - Success
//          01 - Informational
//          10 - Warning
//          11 - Error
//
//      C - is the Customer code flag
//
//      R - is a reserved bit
//
//      Facility - is the facility code
//
//      Code - is the facility's status code
//
//
// Define the facility codes
//


//
// Define the severity codes
//
#define STATUS_SEVERITY_WARNING          0x2
#define STATUS_SEVERITY_SUCCESS          0x0
#define STATUS_SEVERITY_INFORMATIONAL    0x1
#define STATUS_SEVERITY_ERROR            0x3


//
// MessageId: EVENT_BUGCHECK
//
// MessageText:
//
//  The computer has rebooted from a bugcheck.  The bugcheck was:
//  %1.
//  %2.
//  A full dump was not saved.
//
#define EVENT_BUGCHECK                   0x400003E8L

//
// MessageId: EVENT_BUGCHECK_SAVED
//
// MessageText:
//
//  The computer has rebooted from a bugcheck.  The bugcheck was:
//  %1.
//  %2.
//  A dump was saved in: %3.
//
#define EVENT_BUGCHECK_SAVED             0x400003E9L


#endif // _SDEVENT_

