/*++ BUILD Version: 0001    // Increment this if a change has global effects

Copyright (c) 1992  Microsoft Corporation

Module Name:

    atkmsg.h

Abstract:

    Definitions for appletalk events.

Author:

    Nikhil Kamkolkar (nikhilk@microsoft.com)

Revision History:

Notes:

    This file is generated by the MC tool from the atkmsg.mc file.

--*/

#ifndef _ATKMSG_
#define _ATKMSG_


/////////////////////////////////////////////////////////////////////////
// Appletalk Events - Start with the DDP upwards and then the glue code
//                    events
//
/////////////////////////////////////////////////////////////////////////


// Don't use %1 for insertion strings -- the I/O system provides the
// first string (device name).

//
//  Values are 32 bit values layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      Sev - is the severity code
//
//          00 - Success
//          01 - Informational
//          10 - Warning
//          11 - Error
//
//      C - is the Customer code flag
//
//      R - is a reserved bit
//
//      Facility - is the facility code
//
//      Code - is the facility's status code
//
//
// Define the facility codes
//


//
// Define the severity codes
//
#define STATUS_SEVERITY_WARNING          0x2
#define STATUS_SEVERITY_SUCCESS          0x0
#define STATUS_SEVERITY_INFORMATIONAL    0x1
#define STATUS_SEVERITY_ERROR            0x3


//
// MessageId: EVENT_ATALK_NAME_REGISTERED
//
// MessageText:
//
//  The AppleTalk router registered the name %2 on the network
//
#define EVENT_ATALK_NAME_REGISTERED      0x400007D0L

//
// MessageId: EVENT_ATALK_RESOURCE_SHORTAGE
//
// MessageText:
//
//  The Appletalk stack was unable to perform an operation due to a shortage of
//  available resources.
//
#define EVENT_ATALK_RESOURCE_SHORTAGE    0xC00007D1L

//
// MessageId: EVENT_ATALK_CANT_CREATE_DEVICE
//
// MessageText:
//
//  Appletalk could not create the device %2.  Appletalk could not be started.
//
#define EVENT_ATALK_CANT_CREATE_DEVICE   0xC00007D2L

//
// MessageId: EVENT_ATALK_UNLOAD
//
// MessageText:
//
//  Appletalk has successfully unloaded.
//
#define EVENT_ATALK_UNLOAD               0x800007D3L

//
// MessageId: EVENT_ATALK_ROUTING_BIND_FAIL
//
// MessageText:
//
//  The Appletalk stack was unable to bind to a mac when in routing configuration.
//
#define EVENT_ATALK_ROUTING_BIND_FAIL    0xC00007D4L

//
// MessageId: EVENT_ATALK_INIT_NISNOTOPEN
//
// MessageText:
//
//  The AppleTalk stack could not register its name on port %2 as the NIS was
//  not open on the node
//
#define EVENT_ATALK_INIT_NISNOTOPEN      0x800007D5L

//
// MessageId: EVENT_ATALK_INIT_NAMEREGISTERFAILED
//
// MessageText:
//
//  The AppleTalk stack could not register its name on port %2. Verify the name is
//  less than 32 characters long
//
#define EVENT_ATALK_INIT_NAMEREGISTERFAILED 0x800007D6L

//
// MessageId: EVENT_ATALK_INIT_NAMEINUSE
//
// MessageText:
//
//  The AppleTalk stack could not register its name on port %2. It is currently in
//  use on the network. Choose a different name and restart Appletalk.
//
#define EVENT_ATALK_INIT_NAMEINUSE       0x800007D7L

//
// MessageId: EVENT_ATALK_SEEDING_NOTALLOWED
//
// MessageText:
//
//  An invalid port type had seeding information specified on port %2
//
#define EVENT_ATALK_SEEDING_NOTALLOWED   0xC00007D8L

//
// MessageId: EVENT_ATALK_DEFAULTPORT_NOTALLOWED
//
// MessageText:
//
//  An invalid port type (localtalk) was specified as the default port on port %2
//
#define EVENT_ATALK_DEFAULTPORT_NOTALLOWED 0xC00007D9L

//
// MessageId: EVENT_ATALK_INVALID_PORTNAME
//
// MessageText:
//
//  A port name specified was greater than the maximum length allowed (32 characters) on port %2
//
#define EVENT_ATALK_INVALID_PORTNAME     0xC00007DAL

//
// MessageId: EVENT_ATALK_INVALID_NETRANGE
//
// MessageText:
//
//  The Appletalk stack had a port specifying an invalid network range on port %2
//
#define EVENT_ATALK_INVALID_NETRANGE     0xC00007DBL

//
// MessageId: EVENT_ATALK_INITIAL_RANGEOVERLAP
//
// MessageText:
//
//  The network ranges specified for one or more ports overlap with those of the
//  other ports on port %2
//
#define EVENT_ATALK_INITIAL_RANGEOVERLAP 0xC00007DCL

//
// MessageId: EVENT_ATALK_PRAM_OUTOFSYNC
//
// MessageText:
//
//  The Appletalk stack's PRAM values for the network range were not within the
//  network range specified and are being ignored on port %2
//
#define EVENT_ATALK_PRAM_OUTOFSYNC       0x800007DDL

//
// MessageId: EVENT_ATALK_NONEXT_DEFZONE
//
// MessageText:
//
//  A non-extended port had a default zone specified on port %2
//
#define EVENT_ATALK_NONEXT_DEFZONE       0xC00007DEL

//
// MessageId: EVENT_ATALK_INVALID_DEFZONE
//
// MessageText:
//
//  Default zone specified was invalid on port %2
//
#define EVENT_ATALK_INVALID_DEFZONE      0xC00007DFL

//
// MessageId: EVENT_ATALK_NO_DEFZONE
//
// MessageText:
//
//  No default zone was specified on %2.
//
#define EVENT_ATALK_NO_DEFZONE           0xC00007E0L

//
// MessageId: EVENT_ATALK_INVALID_DESIREDZONE
//
// MessageText:
//
//  Desired zone invalid or not specified.
//
#define EVENT_ATALK_INVALID_DESIREDZONE  0xC00007E1L

//
// MessageId: EVENT_ATALK_INVALID_ZONEINLIST
//
// MessageText:
//
//  An invalid zone name specified in the zone list for port %2
//
#define EVENT_ATALK_INVALID_ZONEINLIST   0xC00007E2L

//
// MessageId: EVENT_ATALK_ZONE_NOTINLIST
//
// MessageText:
//
//  The default/desired zone name specified is not in the zone list for port %2
//
#define EVENT_ATALK_ZONE_NOTINLIST       0xC00007E3L

//
// MessageId: EVENT_ATALK_NO_DEFAULTPORT
//
// MessageText:
//
//  No port is configured to be the default port.
//
#define EVENT_ATALK_NO_DEFAULTPORT       0xC00007E4L

//
// MessageId: EVENT_ATALK_INVALID_DEFAULTPORT
//
// MessageText:
//
//  An invalid port is configured to be the default port %2
//
#define EVENT_ATALK_INVALID_DEFAULTPORT  0xC00007E5L

//
// MessageId: EVENT_ATALK_INIT_CONTROLLER
//
// MessageText:
//
//  The adapter on port %2 could not be intialized
//
#define EVENT_ATALK_INIT_CONTROLLER      0xC00007E6L

//
// MessageId: EVENT_ATALK_INIT_FINDADDRESS
//
// MessageText:
//
//  The adapter address on port %2 could not be determined
//
#define EVENT_ATALK_INIT_FINDADDRESS     0xC00007E7L

//
// MessageId: EVENT_ATALK_INIT_COULDNOTGETNODE
//
// MessageText:
//
//  The Appletalk stack failed to acquire a node on port %2
//
#define EVENT_ATALK_INIT_COULDNOTGETNODE 0xC00007E8L

//
// MessageId: EVENT_ATALK_SEEDROUTER_NONETRANGE
//
// MessageText:
//
//  A seeding port had no network range specified on port %2
//
#define EVENT_ATALK_SEEDROUTER_NONETRANGE 0xC00007E9L

//
// MessageId: EVENT_ATALK_SEEDROUTER_NOZONELIST
//
// MessageText:
//
//  A seeding port had no zone list specified on port %2
//
#define EVENT_ATALK_SEEDROUTER_NOZONELIST 0xC00007EAL

//
// MessageId: EVENT_ATALK_SEEDROUTER_TOOMANYZONES
//
// MessageText:
//
//  A seeding port had too many zones specified on port %2
//
#define EVENT_ATALK_SEEDROUTER_TOOMANYZONES 0xC00007EBL

//
// MessageId: EVENT_ATALK_INVALID_ZONEINFO
//
// MessageText:
//
//  A port had invalid zone information.
//
#define EVENT_ATALK_INVALID_ZONEINFO     0xC00007ECL

//
// MessageId: EVENT_ATALK_NONEXTENDED_ZONEINFOINVALID
//
// MessageText:
//
//  Either the default zone was null or the zone list was empty on an non-extended
//  port %2
//
#define EVENT_ATALK_NONEXTENDED_ZONEINFOINVALID 0xC00007EDL

//
// MessageId: EVENT_ATALK_EXTRAZONESINLIST
//
// MessageText:
//
//  There was more than one zone specified in the zone list for a non-extended port %2
//
#define EVENT_ATALK_EXTRAZONESINLIST     0xC00007EEL

//
// MessageId: EVENT_ATALK_OPENATALKKEY
//
// MessageText:
//
//  The Appletalk stack was unable to open the appletalk key in the registry.
//
#define EVENT_ATALK_OPENATALKKEY         0xC00007EFL

//
// MessageId: EVENT_ATALK_INVALID_BINDINGS
//
// MessageText:
//
//  The Appletalk stack had problems with the bindings specified
//
#define EVENT_ATALK_INVALID_BINDINGS     0xC00007F0L

//
// MessageId: EVENT_ATALK_NO_ENABLEROUTERKEY
//
// MessageText:
//
//  The Appletalk stack was unable to find the EnableRouter key in the registry.
//
#define EVENT_ATALK_NO_ENABLEROUTERKEY   0xC00007F1L


//
//     ROUTER Error Codes
//

//
// MessageId: EVENT_ATALK_ROUTER_NOTROUTINGPORT
//
// MessageText:
//
//  The Appletalk stack attempted to start the router on a port not configured
//  to be one %2
//
#define EVENT_ATALK_ROUTER_NOTROUTINGPORT 0xC00007F2L

//
// MessageId: EVENT_ATALK_ROUTER_COULDNOTGETNODE
//
// MessageText:
//
//  The Appletalk router could not start on port %2 as it could not acquire a
//  node
//
#define EVENT_ATALK_ROUTER_COULDNOTGETNODE 0xC00007F3L

//
// MessageId: EVENT_ATALK_ROUTER_ZIPRTMPERROR
//
// MessageText:
//
//  The Appletalk router could not start ZIP/RTMP processes on port %2
//
#define EVENT_ATALK_ROUTER_ZIPRTMPERROR  0xC00007F4L

//
// MessageId: EVENT_ATALK_ROUTER_RELEASENODE
//
// MessageText:
//
//  The Appletalk router could not release a node it acquired on port %2
//
#define EVENT_ATALK_ROUTER_RELEASENODE   0xC00007F5L

//
// MessageId: EVENT_ATALK_ROUTERSTART
//
// MessageText:
//
//  The Appletalk router could not be started on port %2
//
#define EVENT_ATALK_ROUTERSTART          0xC00007F6L


//
//     AARP Error Codes
//

//
// MessageId: EVENT_ATALK_INVALIDAARPPACKET
//
// MessageText:
//
//  The Appletalk stack received an invalid aarp packet on port %2
//
#define EVENT_ATALK_INVALIDAARPPACKET    0xC00007F7L

//
// MessageId: EVENT_ATALK_AARP_SEND_FAIL
//
// MessageText:
//
//  An AARP packet could not be sent on port %2
//
#define EVENT_ATALK_AARP_SEND_FAIL       0xC00007F8L

//
// MessageId: EVENT_ATALK_OPENZIPSOCKET
//
// MessageText:
//
//  The Zone Information Socket could not be opened on a new node being
//  acquired, and the acquired node is being released on port %2
//
#define EVENT_ATALK_OPENZIPSOCKET        0xC00007F9L

//
// MessageId: EVENT_ATALK_STARTUPRANGENODE
//
// MessageText:
//
//  The Appletalk stack is releasing a node acquired on the port %2 as
//  the non-seeding routing port is not seeded by any router on the net
//
#define EVENT_ATALK_STARTUPRANGENODE     0x800007FAL

//
// MessageId: EVENT_ATALK_INITIALRANGENODE
//
// MessageText:
//
//  The Appletalk stack is releasing a node acquired on the port %2 as
//  the node was obtained in the initial range. Node is now being acquired
//  in the seeded range.
//
#define EVENT_ATALK_INITIALRANGENODE     0x800007FBL

//
// MessageId: EVENT_ATALK_AMT_INVALIDSOURCE
//
// MessageText:
//
//  The Appletalk stack did not insert an entry in the Address Mapping Table on
//  port %2 as it contained an invalid source address
//
#define EVENT_ATALK_AMT_INVALIDSOURCE    0xC00007FCL


//
//     ZIP Error Codes
//

//
// MessageId: EVENT_ATALK_ZIPSENDPACKET
//
// MessageText:
//
//  The Appletalk stack was unable to send a ZIP packet on port %2
//
#define EVENT_ATALK_ZIPSENDPACKET        0x800007FDL

//
// MessageId: EVENT_ATALK_ZIPSOCKETCLOSE
//
// MessageText:
//
//  The Appletalk stack was unable to close a socket opened for a ZIP request
//  on port %2
//
#define EVENT_ATALK_ZIPSOCKETCLOSE       0x800007FEL


//
//     NODE Error Codes
//

//
// MessageId: EVENT_ATALK_NODE_OPENSOCKETS
//
// MessageText:
//
//  The Appletalk stack could not open RTMP/NBP/EP listeners on a node created on
//  port %2
//
#define EVENT_ATALK_NODE_OPENSOCKETS     0xC00007FFL

//
// MessageId: EVENT_ATALK_NODE_CLOSESOCKETS
//
// MessageText:
//
//  The Appletalk stack could not close sockets on a node on port %2 and so the
//  node may not be released properly
//
#define EVENT_ATALK_NODE_CLOSESOCKETS    0xC0000800L

//
// MessageId: EVENT_ATALK_OPENSOCKETFAILED
//
// MessageText:
//
//  The Appletalk stack could not open a socket even after acquiring a new node
//
#define EVENT_ATALK_OPENSOCKETFAILED     0xC0000801L


//
//     DEPEND Level Error Codes
//


//
//     NDIS Level Error Codes
//

//
// MessageId: EVENT_ATALK_REGISTERPROTOCOL
//
// MessageText:
//
//  Appletalk failed to register itself with the NDIS wrapper.
//
#define EVENT_ATALK_REGISTERPROTOCOL     0xC0000802L

//
// MessageId: EVENT_ATALK_DEREGISTERPROTOCOL
//
// MessageText:
//
//  Appletalk failed to deregister itself with the NDIS wrapper.
//
#define EVENT_ATALK_DEREGISTERPROTOCOL   0xC0000803L

//
// MessageId: EVENT_ATALK_OPENADAPTER
//
// MessageText:
//
//  Appletalk failed to open the adapter (bind to the mac) %2.
//
#define EVENT_ATALK_OPENADAPTER          0xC0000804L

//
// MessageId: EVENT_ATALK_CLOSEADAPTER
//
// MessageText:
//
//  Appletalk failed to close the adapter %2.
//
#define EVENT_ATALK_CLOSEADAPTER         0x80000805L

//
// MessageId: EVENT_ATALK_NOTBOUNDTOMAC
//
// MessageText:
//
//  Appletalk is not bound to the adapter %2. Request for the adapter ignored.
//
#define EVENT_ATALK_NOTBOUNDTOMAC        0xC0000806L

//
// MessageId: EVENT_ATALK_STATIONADDRESS
//
// MessageText:
//
//  Appletalk failed to get the station address for adapter %2.
//
#define EVENT_ATALK_STATIONADDRESS       0x80000807L

//
// MessageId: EVENT_ATALK_LOOKAHEADSIZE
//
// MessageText:
//
//  Appletalk failed to set the lookahead size for adapter %2.
//
#define EVENT_ATALK_LOOKAHEADSIZE        0x80000808L

//
// MessageId: EVENT_ATALK_PACKETFILTER
//
// MessageText:
//
//  Appletalk failed to set the packet filter for adapter %2.
//
#define EVENT_ATALK_PACKETFILTER         0x80000809L

//
// MessageId: EVENT_ATALK_NDISRESOURCES
//
// MessageText:
//
//  Appletalk failed to allocate resources from the NDIS wrapper.
//
#define EVENT_ATALK_NDISRESOURCES        0xC000080AL

//
// MessageId: EVENT_ATALK_AARPPACKET
//
// MessageText:
//
//  An AARP packet was not completely available in the lookahead data from NDIS
//  on adapter %2.
//
#define EVENT_ATALK_AARPPACKET           0x8000080BL

//
// MessageId: EVENT_ATALK_PACKETINVALID
//
// MessageText:
//
//  Packet received on adapter %2 contained errors and is not being accepted.
//
#define EVENT_ATALK_PACKETINVALID        0x8000080CL

//
//     GENERAL Error Codes
//
//
// MessageId: EVENT_ATALK_RESOURCES
//
// MessageText:
//
//  Appletalk could not allocate resources needed for its tasks.
//
#define EVENT_ATALK_RESOURCES            0xC000080DL

//
// MessageId: EVENT_ATALK_MEMORYRESOURCES
//
// MessageText:
//
//  Appletalk could not allocate memory needed for its tasks.
//
#define EVENT_ATALK_MEMORYRESOURCES      0xC000080EL

//
// MessageId: EVENT_ATALK_INTERNALERROR
//
// MessageText:
//
//  A fatal internal error was detected in the Appletalk stack
//
#define EVENT_ATALK_INTERNALERROR        0xC000080FL


#endif // _ATKMSG

