/*++ BUILD Version: 0001    // Increment this if a change has global effects

Copyright (c) 1991  Microsoft Corporation

Module Name:

    saclmsg.h

Abstract:

    This module contains the definition of the setacl messages.

Author:

    Sunil Pai (sunilp) Dec 18, 1992.

Revision History:

Notes:

    This file is generated by the MC tool from the saclmsg.mc
    file.

--*/

#ifndef _SETACLMSG_
#define _SETACLMSG_


//
//  Values are 32 bit values layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      Sev - is the severity code
//
//          00 - Success
//          01 - Informational
//          10 - Warning
//          11 - Error
//
//      C - is the Customer code flag
//
//      R - is a reserved bit
//
//      Facility - is the facility code
//
//      Code - is the facility's status code
//
//
// Define the facility codes
//


//
// Define the severity codes
//


//
// MessageId: WORK_MESSAGE
//
// MessageText:
//
//  Setting Security on System Files %0
//
#define WORK_MESSAGE                     ((ULONG)0x00000001L)

//
// MessageId: FAILED_MESSAGE
//
// MessageText:
//
//  > Failed
//
#define FAILED_MESSAGE                   ((ULONG)0x00000002L)

//
// MessageId: DONE_MESSAGE
//
// MessageText:
//
//  > Done
//
#define DONE_MESSAGE                     ((ULONG)0x00000003L)

#endif // _SETACLMSG_
