/**********************************************************************/
/**                       Microsoft Windows NT                       **/
/**                Copyright(c) Microsoft Corp., 1993                **/
/**********************************************************************/

/*
    dnsmsg.h

    This file is generated by the MC tool from the DNSMSG.MC message
    file.


    FILE HISTORY:
        DavidTr     01-Aug-1993 Created.

*/


#ifndef _DNSMSG_H_
#define _DNSMSG_H_

//
//  Values are 32 bit values layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      Sev - is the severity code
//
//          00 - Success
//          01 - Informational
//          10 - Warning
//          11 - Error
//
//      C - is the Customer code flag
//
//      R - is a reserved bit
//
//      Facility - is the facility code
//
//      Code - is the facility's status code
//
//
// Define the facility codes
//


//
// Define the severity codes
//


//
// MessageId: DNS_EVENT_CANNOT_ALLOCATE_RECORD
//
// MessageText:
//
//  DNS Server could not allocate memory for resource record %1.
//
#define DNS_EVENT_CANNOT_ALLOCATE_RECORD 0x80000001L

//
// MessageId: DNS_EVENT_CANNOT_INITIALIZE_WINSOCK
//
// MessageText:
//
//  DNS Server could not initialize the socket library.  The data is the error.
//
#define DNS_EVENT_CANNOT_INITIALIZE_WINSOCK 0xC0000002L

//
// MessageId: DNS_EVENT_OUT_OF_MEMORY
//
// MessageText:
//
//  DNS Server was unable to service a client request due a shortage of available memory.
//
#define DNS_EVENT_OUT_OF_MEMORY          0xC0000003L

//
// MessageId: DNS_EVENT_CANNOT_LOCATE_DNS_UDP
//
// MessageText:
//
//  DNS Server could not locate the DNS service for UDP.  The data is the error.
//
#define DNS_EVENT_CANNOT_LOCATE_DNS_UDP  0xC0000004L

//
// MessageId: DNS_EVENT_CANNOT_LOCATE_DNS_TCP
//
// MessageText:
//
//  DNS Server could not locate the DNS service for TCP.  The data is the error.
//
#define DNS_EVENT_CANNOT_LOCATE_DNS_TCP  0xC0000005L

//
// MessageId: DNS_EVENT_CANNOT_CREATE_CONNECTION_SOCKET
//
// MessageText:
//
//  DNS Server could not create the main connection socket.  The data is the error.
//
#define DNS_EVENT_CANNOT_CREATE_CONNECTION_SOCKET 0xC0000006L

//
// MessageId: DNS_EVENT_CANNOT_BIND_CONNECTION_SOCKET
//
// MessageText:
//
//  DNS Server could not bind the main connection socket.  The data is the error.
//
#define DNS_EVENT_CANNOT_BIND_CONNECTION_SOCKET 0xC0000007L

//
// MessageId: DNS_EVENT_CANNOT_LISTEN_CONNECTION_SOCKET
//
// MessageText:
//
//  DNS Server could not listen on the main connection socket.  The data is the error.
//
#define DNS_EVENT_CANNOT_LISTEN_CONNECTION_SOCKET 0xC0000008L

//
// MessageId: DNS_EVENT_CANNOT_CREATE_DATAGRAM_SOCKET
//
// MessageText:
//
//  DNS Server could not create the main datagram socket.  The data is the error.
//
#define DNS_EVENT_CANNOT_CREATE_DATAGRAM_SOCKET 0xC0000009L

//
// MessageId: DNS_EVENT_CANNOT_BIND_DATAGRAM_SOCKET
//
// MessageText:
//
//  DNS Server could not bind the main datagram socket.  The data is the error.
//
#define DNS_EVENT_CANNOT_BIND_DATAGRAM_SOCKET 0xC000000AL

//
// MessageId: DNS_EVENT_CANNOT_CREATE_INIT_WORKER
//
// MessageText:
//
//  DNS Server could not create an initial worker thread.  The data is the error.
//
#define DNS_EVENT_CANNOT_CREATE_INIT_WORKER 0xC000000BL

//
// MessageId: DNS_EVENT_CANNOT_CREATE_ADD_WORKER
//
// MessageText:
//
//  DNS Server could not create an additional worker thread.  The data is the error.
//
#define DNS_EVENT_CANNOT_CREATE_ADD_WORKER 0x8000000CL

//
// MessageId: DNS_EVENT_SYSTEM_CALL_FAILED
//
// MessageText:
//
//  A call to a system service failed unexpectedly.  The data is the error.
//
#define DNS_EVENT_SYSTEM_CALL_FAILED     0xC000000DL


#endif  // _DNSMSG_H_

